/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_color_free: (a: number, b: number) => void;
export const __wbg_node_free: (a: number, b: number) => void;
export const __wbg_stickfigure_free: (a: number, b: number) => void;
export const color_alpha: (a: number) => number;
export const color_blue: (a: number) => number;
export const color_fromHex: (a: number, b: number) => [number, number, number];
export const color_green: (a: number) => number;
export const color_new: (a: number, b: number, c: number, d: number) => number;
export const color_red: (a: number) => number;
export const color_toHex: (a: number) => [number, number];
export const node_addChild: (a: number, b: any) => [number, number, number];
export const node_children: (a: number) => [number, number];
export const node_colorHex: (a: number) => [number, number];
export const node_drawIndex: (a: number) => number;
export const node_length: (a: number) => number;
export const node_localAngle: (a: number) => number;
export const node_nodeType: (a: number) => number;
export const node_scale: (a: number) => number;
export const node_thickness: (a: number) => number;
export const node_useSegmentColor: (a: number) => number;
export const node_useSegmentScale: (a: number) => number;
export const stickfigure_addPolyfill: (a: number, b: any) => [number, number];
export const stickfigure_allNodeIndices: (a: number) => [number, number];
export const stickfigure_build: (a: number) => number;
export const stickfigure_colorHex: (a: number) => [number, number];
export const stickfigure_fromBytes: (a: number, b: number) => [number, number, number];
export const stickfigure_getNode: (a: number, b: number) => [number, number, number];
export const stickfigure_new: () => number;
export const stickfigure_rootNode: (a: number) => number;
export const stickfigure_scale: (a: number) => number;
export const stickfigure_setVersion: (a: number, b: number) => void;
export const stickfigure_set_build: (a: number, b: number) => void;
export const stickfigure_set_colorHex: (a: number, b: number, c: number) => [number, number];
export const stickfigure_set_scale: (a: number, b: number) => void;
export const stickfigure_toBytes: (a: number) => [number, number, number, number];
export const stickfigure_version: (a: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
